/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ems;

import javax.swing.*;

/**
 *
 * @author dell
 */
public class LoginForm extends javax.swing.JPanel {

    private static int USER_PERSON_ID;
    private static String USER_ID;
    private static String USER_TYPE;

    private EMS ems = null;

    /**
     * Creates new form LoginForm
     */
    public LoginForm(EMS ems) {
        this.ems = ems;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        upass = new javax.swing.JPasswordField();
        btnSubmit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setPreferredSize(new java.awt.Dimension(570, 370));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 146, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 213, -1, -1));

        id.setBackground(new java.awt.Color(255, 255, 204));
        id.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        id.setText("wana");
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 143, 151, -1));

        upass.setBackground(new java.awt.Color(255, 255, 204));
        upass.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        upass.setText("12");
        add(upass, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 210, 151, -1));

        btnSubmit.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btnSubmit.setText("Login");
        btnSubmit.setToolTipText("");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 289, -1, -1));

        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Registration");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 295, -1, -1));

        jLabel3.setBackground(new java.awt.Color(51, 102, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome To Event Management System");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 15, 490, 84));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ems/bg15.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.ems.addComponent(new RegistrationForm(this.ems));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String userId = id.getText();
        String password = upass.getText();
        if (checkValidation() && LoginDao.validationLogin(userId, password)) {
            //JOptionPane.showMessageDialog(LoginForm.this, "Login Successfull..");
            Person person = RegistrationDao.getPerson(userId);
            USER_PERSON_ID = person.getId();
            USER_ID = userId;
            USER_TYPE = person.getUserType();

            if(USER_TYPE.equalsIgnoreCase("MANAGER")){
                this.ems.enableToolbarAsManager();
            }else{
                this.ems.enableToolbarAsClient();
            }
            
            
            this.ems.addComponent(new ViewBookingForm(this.ems));
        } else {
            JOptionPane.showMessageDialog(LoginForm.this, "Invalid Details..");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private boolean checkValidation() {
        String userId = id.getText();
        String password = upass.getText();
        if (userId.trim().isEmpty()) {
            JOptionPane.showMessageDialog(LoginForm.this, "Enter ID");
            id.grabFocus();
            return false;
        } else if (password.trim().isEmpty()) {
            JOptionPane.showMessageDialog(LoginForm.this, "Enter Password");
            upass.grabFocus();
            return false;
        }
        return true;
    }

    public static int getUserPersonId() {
        return USER_PERSON_ID;
    }

    public static String getUserId() {
        return USER_ID;
    }

    public static String getUserType() {
        return USER_TYPE;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField upass;
    // End of variables declaration//GEN-END:variables
}
