/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ems;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;

/**
 *
 * @author dell
 */
public class RegistrationForm extends javax.swing.JPanel {

    private EMS ems = null;
    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm(EMS ems) {
        this.ems = ems;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        userType = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        gender = new javax.swing.JComboBox<>();
        email = new javax.swing.JTextField();
        cpass = new javax.swing.JPasswordField();
        btnCancel = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setPreferredSize(new java.awt.Dimension(700, 376));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 51, 65, 30));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mobile");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 65, 38));

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gender");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 65, 38));

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User Type");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, 38));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 73, 38));

        jLabel6.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 73, 38));

        jLabel7.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirm Password");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, 36));

        jLabel8.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, 36));

        mobile.setBackground(new java.awt.Color(255, 255, 204));
        mobile.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 199, -1));

        name.setBackground(new java.awt.Color(255, 255, 204));
        name.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 199, -1));

        userType.setBackground(new java.awt.Color(255, 255, 204));
        userType.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        userType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Manager", "Client" }));
        add(userType, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 166, -1));

        address.setBackground(new java.awt.Color(255, 255, 204));
        address.setColumns(20);
        address.setLineWrap(true);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 199, -1));

        gender.setBackground(new java.awt.Color(255, 255, 204));
        gender.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Female", "Male" }));
        add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 195, -1));

        email.setBackground(new java.awt.Color(255, 255, 204));
        email.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 170, -1));

        cpass.setBackground(new java.awt.Color(255, 255, 204));
        cpass.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        add(cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 170, -1));

        btnCancel.setFont(new java.awt.Font("Cambria Math", 3, 18)); // NOI18N
        btnCancel.setText("Back");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 110, 40));

        btnRegister.setFont(new java.awt.Font("Cambria Math", 3, 18)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, 40));

        pass.setBackground(new java.awt.Color(255, 255, 204));
        pass.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 170, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ems/bg15.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 680, 360));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        if(checkValidation()){
            String uname = name.getText();
            String ugender = (String)gender.getSelectedItem();
            String umobile = mobile.getText();
            String uaddress = address.getText();
            String utype = (String)userType.getSelectedItem();
            String uemail = email.getText();
            String upass = pass.getText();
            Person person = null;
            Login login = new Login(0,uemail,upass);
            if(utype.equals("Manager")){
                person = new Manager(uname,ugender,umobile,uaddress,uemail,utype);               
            }else if(utype.equals("Client")){
                person = new Customer(uname,ugender,umobile,uaddress,uemail,utype);
            }
            boolean flag = RegistrationDao.save(person, login);
            if(flag){
                JOptionPane.showMessageDialog(RegistrationForm.this, "Registration successfull...");
            }else{
                JOptionPane.showMessageDialog(RegistrationForm.this, "something went wrong...");
            }
            reSet();
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.ems.addComponent(new LoginForm(this.ems));
    }//GEN-LAST:event_btnCancelActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private boolean checkValidation(){
        if(name.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Enter Name");
            name.grabFocus();
            return false;
        }else if(gender.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Select gender");
            return false;
        }else if(mobile.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Enter Mobile");
            mobile.grabFocus();
            return false;
        }else if(address.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Enter Address");
            address.grabFocus();
            return false;
        }else if(userType.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Select UserType");
            return false;
        }else if(email.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Enter Email");
            email.grabFocus();
            return false;
        }else if(!isEmailValidPattern()){    
            JOptionPane.showMessageDialog(RegistrationForm.this, "Invalid Email Pattern");
            return false;
        }else if(RegistrationDao.isEmailExited(email.getText())){
           JOptionPane.showMessageDialog(RegistrationForm.this, "Email already Exist..");
           return false;
        }else if(pass.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Enter Password");
            pass.grabFocus();
            return false;
        }else if(cpass.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(RegistrationForm.this, "Enter Confirm Password");
            cpass.grabFocus();
            return false;
        }else if((pass.getText()).equals(cpass.getText())){
            return true;
        }else{
            JOptionPane.showMessageDialog(RegistrationForm.this, "Password not matched..");
        }
        return false;
}
    private boolean isEmailValidPattern(){
        String regex = "^(.+)@(\\S+)$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(email.getText());
        return matcher.matches();
    }
    private void reSet(){
        name.setText(null);
        gender.setSelectedIndex(0);
        mobile.setText(null);
        address.setText(null);
        userType.setSelectedIndex(0);
        email.setText(null);
        pass.setText(null);
        cpass.setText(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPasswordField cpass;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pass;
    private javax.swing.JComboBox<String> userType;
    // End of variables declaration//GEN-END:variables
}
