/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ems;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author dell
 */
public class ShowBookDetails extends javax.swing.JPanel {

    /**
     * Creates new form ShowBookDetails
     */
    private EMS ems;
    private String eventID;
    public ShowBookDetails(EMS ems, String eventID) {
        this.ems = ems;
        this.eventID = eventID;
        initComponents();
        setData(eventID);
    }

    public ShowBookDetails() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        noOfGuest = new javax.swing.JTextField();
        venueType = new javax.swing.JTextField();
        venueName = new javax.swing.JTextField();
        stDate = new javax.swing.JTextField();
        endDate = new javax.swing.JTextField();
        foodCost = new javax.swing.JTextField();
        eventType = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        equipList = new javax.swing.JList<>();
        bkID = new javax.swing.JTextField();
        equipCost = new javax.swing.JTextField();
        totalCost = new javax.swing.JTextField();
        venueCost = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        foodList = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setEnabled(false);
        setPreferredSize(new java.awt.Dimension(879, 733));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Book Event Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 42, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Event Type");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel3.setText("Booking ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 105, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Venue Type");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 177, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Venue");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Event End Date");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No Of Guest");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Event Start Date");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Equipments");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        jLabel10.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Equipments Cost");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, -1, -1));

        jLabel11.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Food Items");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel13.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Food Items Cost");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, -1, -1));

        imageLabel.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 356, 308));

        jLabel15.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Total Cost");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, -1, -1));

        jLabel16.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Venue Cost");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, -1, -1));

        btnBack.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 646, 104, 54));

        noOfGuest.setBackground(new java.awt.Color(255, 255, 204));
        noOfGuest.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        noOfGuest.setEnabled(false);
        add(noOfGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 177, -1));

        venueType.setBackground(new java.awt.Color(255, 255, 204));
        venueType.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        venueType.setEnabled(false);
        add(venueType, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 177, -1));

        venueName.setBackground(new java.awt.Color(255, 255, 204));
        venueName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        venueName.setEnabled(false);
        add(venueName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 177, -1));

        stDate.setBackground(new java.awt.Color(255, 255, 204));
        stDate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        stDate.setEnabled(false);
        add(stDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 177, -1));

        endDate.setBackground(new java.awt.Color(255, 255, 204));
        endDate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        endDate.setEnabled(false);
        add(endDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 177, -1));

        foodCost.setBackground(new java.awt.Color(255, 255, 204));
        foodCost.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        foodCost.setEnabled(false);
        add(foodCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 165, -1));

        eventType.setBackground(new java.awt.Color(255, 255, 204));
        eventType.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        eventType.setEnabled(false);
        add(eventType, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 177, -1));

        equipList.setBackground(new java.awt.Color(255, 255, 204));
        equipList.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        equipList.setEnabled(false);
        jScrollPane1.setViewportView(equipList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 180, 130));

        bkID.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bkID.setEnabled(false);
        add(bkID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 165, -1));

        equipCost.setBackground(new java.awt.Color(255, 255, 204));
        equipCost.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        equipCost.setEnabled(false);
        add(equipCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 165, -1));

        totalCost.setBackground(new java.awt.Color(255, 255, 204));
        totalCost.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        totalCost.setEnabled(false);
        add(totalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 580, 165, -1));

        venueCost.setBackground(new java.awt.Color(255, 255, 204));
        venueCost.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        venueCost.setEnabled(false);
        add(venueCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 165, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 204));

        foodList.setBackground(new java.awt.Color(255, 255, 204));
        foodList.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        foodList.setEnabled(false);
        jScrollPane2.setViewportView(foodList);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 177, 120));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ems/bg15.png"))); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 860, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.ems.addComponent(new ViewBookingForm(this.ems));

    }//GEN-LAST:event_btnBackActionPerformed

    private void setData(String eventID){
        Event event = EventDao.getEventDetails(eventID);
        Event eventFd = EventDao.getFoodDetails(eventID);
        Event eventEq = EventDao.getEquipmentDetails(eventID);
        bkID.setText(eventID);
        bkID.setVisible(false);
        jLabel3.setVisible(false);
        eventType.setText(event.getEventType());
        venueType.setText(event.getVenueType());
        venueName.setText(event.getVenueName());
        stDate.setText(""+event.getEventStartDate());
        endDate.setText(""+event.getEventEndDate());
        noOfGuest.setText(""+event.getNoOfGuest());
        venueCost.setText(""+event.getVenueCost());
        foodCost.setText(""+(eventFd.getFoodCost()*event.getNoOfGuest()));
        equipCost.setText(""+eventEq.getEquipmentCost());
        totalCost.setText(""+(event.getVenueCost() +eventEq.getEquipmentCost()+(eventFd.getFoodCost()*event.getNoOfGuest())));
        setFoodItems(eventFd.getFoodItems());
        setEquipmentList(eventEq.getEquipments());
        imageLabel.setIcon(new ImageIcon(event.getVenueImage()));
        
    }
    private void setFoodItems(ArrayList<FoodManagement> list){
        DefaultListModel<FoodManagement> foodlistModel = new DefaultListModel<>();
        for (FoodManagement fi : list) {
            foodlistModel.addElement(fi);
        }
        foodList.setModel(foodlistModel);
    }
    
    private void setEquipmentList(ArrayList<EquipmentManagement> list){
        DefaultListModel<EquipmentManagement> equiplistModel = new DefaultListModel<>();
        for (EquipmentManagement eq : list) {
            equiplistModel.addElement(eq);
        }
        equipList.setModel(equiplistModel);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bkID;
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField endDate;
    private javax.swing.JTextField equipCost;
    private javax.swing.JList<EquipmentManagement> equipList;
    private javax.swing.JTextField eventType;
    private javax.swing.JTextField foodCost;
    private javax.swing.JList<FoodManagement> foodList;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField noOfGuest;
    private javax.swing.JTextField stDate;
    private javax.swing.JTextField totalCost;
    private javax.swing.JTextField venueCost;
    private javax.swing.JTextField venueName;
    private javax.swing.JTextField venueType;
    // End of variables declaration//GEN-END:variables
}
